### ISSUE TITLE
Apache error during the build step

### ISSUE THREAD

**Issue by RomanHyde** [rdearman/LWT_Docker#2]
Hi there, I've been following along on my M1 Macbook. I have docker installed but it's throwing an error in regards to apache.

```
user@user-MBP lwt_html % docker-compose build lwt
[+] Building 2.2s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                        0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 34B                                           0.0s
 => [internal] load metadata for docker.io/library/php:7.2.7-apache        2.1s
 => [internal] load build context                                          0.0s
 => => transferring context: 2B                                            0.0s
 => CANCELED [1/4] FROM docker.io/library/php:7.2.7-apache@sha256:7d9df9c  0.0s
 => => resolve docker.io/library/php:7.2.7-apache@sha256:7d9df9c4445e4ce1  0.0s
 => => sha256:7d9df9c4445e4ce15427abf876e5cfbbc351669ffdf 2.06kB / 2.06kB  0.0s
 => => sha256:3a923918bfa04eed7e5c9d6d0ddf5be4ec7ca2482cc 3.45kB / 3.45kB  0.0s
 => => sha256:a1a58675e0e2d11292e1aaca61fcf99ef258b66fe 12.83kB / 12.83kB  0.0s
 => CACHED [2/4] RUN apt update;     apt upgrade;     apt-get install -y   0.0s
 => CACHED [3/4] RUN docker-php-ext-install mysqli                         0.0s
 => ERROR [4/4] COPY ./lwt_html /var/www/html                              0.0s
------
 > [4/4] COPY ./lwt_html /var/www/html:
------
failed to solve: failed to compute cache key: "/lwt_html" not found: not found```

I've posted on the instruction video too but I thought I'd reach out here just in case you see it. Any assistance would be greatly appreciated! Thanks.

**Comment by rdearman** [comment]
> Hi there, I've been following along on my M1 Macbook. I have docker installed but it's throwing an error in regards to apache.
> 
> ```
> user@user-MBP lwt_html % docker-compose build lwt
> [+] Building 2.2s (8/8) FINISHED
>  => [internal] load build definition from Dockerfile                       0.0s
>  => => transferring dockerfile: 32B                                        0.0s
>  => [internal] load .dockerignore                                          0.0s
>  => => transferring context: 34B                                           0.0s
>  => [internal] load metadata for docker.io/library/php:7.2.7-apache        2.1s
>  => [internal] load build context                                          0.0s
>  => => transferring context: 2B                                            0.0s
>  => CANCELED [1/4] FROM docker.io/library/php:7.2.7-apache@sha256:7d9df9c  0.0s
>  => => resolve docker.io/library/php:7.2.7-apache@sha256:7d9df9c4445e4ce1  0.0s
>  => => sha256:7d9df9c4445e4ce15427abf876e5cfbbc351669ffdf 2.06kB / 2.06kB  0.0s
>  => => sha256:3a923918bfa04eed7e5c9d6d0ddf5be4ec7ca2482cc 3.45kB / 3.45kB  0.0s
>  => => sha256:a1a58675e0e2d11292e1aaca61fcf99ef258b66fe 12.83kB / 12.83kB  0.0s
>  => CACHED [2/4] RUN apt update;     apt upgrade;     apt-get install -y   0.0s
>  => CACHED [3/4] RUN docker-php-ext-install mysqli                         0.0s
>  => ERROR [4/4] COPY ./lwt_html /var/www/html                              0.0s
> ------
>  > [4/4] COPY ./lwt_html /var/www/html:
> ------
> failed to solve: failed to compute cache key: "/lwt_html" not found: not found```
> 
> I've posted on the instruction video too but I thought I'd reach out here just in case you see it. Any assistance would be greatly appreciated! Thanks.
> ```

Have you downloaded the LWT source code into the docker directory? If you have already downloaded the lwt source and moved it into the directory, it might be a permissions problem.

**Comment by RomanHyde** [comment]
Hi Rick, thank you for the help, you were right, it was a permissions problem! Thank you!
